#!/usr/bin/env python3
"""
Sound Design RAG - Setup Script.

Auto-configures .env from Hermes' auth.json so the RAG Just Works.
Run this once after cloning.
"""
import json
import os
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.absolute()
ENV_PATH = PROJECT_ROOT / ".env"
AUTH_PATH = Path.home() / "AppData/Local/hermes/auth.json"


def find_best_credential(auth):
    """Find the best available API credential from Hermes."""
    pool = auth.get("credential_pool", {})

    # Priority: nous agent_key (long-lived OAuth) > deepseek > nvidia > openrouter
    for provider_name in ["nous", "deepseek", "nvidia", "openrouter"]:
        entries = pool.get(provider_name, [])
        if not entries:
            continue
        entry = entries[0]

        # Nous uses OAuth with an agent_key
        if provider_name == "nous":
            key = entry.get("agent_key") or entry.get("access_token")
            base_url = entry.get("inference_base_url", "https://inference-api.nousresearch.com/v1")
            if key:
                return key, base_url, f"{provider_name}/gpt-4o-mini"

        # Others use api_key
        key_source = entry.get("source", "")
        base_url = entry.get("base_url", "")
        label = entry.get("label", "").lower()

        if key_source.startswith("env:"):
            env_var = key_source.split("env:", 1)[1]
            val = os.environ.get(env_var) or os.environ.get(env_var.upper())
            if val:
                return val, base_url, f"{provider_name}/chat"

    return None, None, None


def main():
    # Check if .env already has a real key
    if ENV_PATH.exists():
        content = ENV_PATH.read_text()
        if "LLM_API_KEY=sk-" in content or "LLM_API_KEY=fm" in content:
            print("✅ .env already has an API key configured")
            return

    if not AUTH_PATH.exists():
        print("⚠️  Hermes auth.json not found. Create .env manually with:")
        print("   LLM_API_KEY=your-api-key")
        print("   LLM_BASE_URL=https://api.openai.com/v1")
        return

    with open(AUTH_PATH) as f:
        auth = json.load(f)

    key, base_url, model = find_best_credential(auth)

    if not key:
        print("⚠️  No API key found in Hermes auth. Create .env manually.")
        return

    # Write .env
    env_content = f"""# Auto-generated by setup.py from Hermes auth
LLM_API_KEY={key}
LLM_BASE_URL={base_url}
LLM_MODEL={model}

# Embedding: "local" uses built-in ONNX all-MiniLM-L6-v2 (free)
EMBEDDING_MODE=local

# Server
HOST=0.0.0.0
PORT=8000
"""
    ENV_PATH.write_text(env_content)
    print(f"✅ .env created with {base_url} and key ({len(key)} chars)")
    print(f"   Model: {model}")


if __name__ == "__main__":
    main()
